version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    container_name: spring-renting
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: renting
      MYSQL_ROOT_PASSWORD: root
    volumes: 
      - spring-renting:/var/lib/mysql

volumes:
  spring-renting:
