spring:
  jpa:
    naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3308/renting?createDatabaseIfNotExist=true
    username: root
    password: root
    pool-size: 100
