spring:
  jpa:
    naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
      ddl-auto: update
    properties:
      hibernate:
        formate_sql: true
  datasource:
    url: jdbc:mysql://localhost:3308/renting?createDatabaseIfNotExist=true
    username: root
    password: root
    pool-size: 100
